### ISSUE TITLE
What charset to use?

### ISSUE THREAD

**Issue by OuesFa** [logstash-plugins/logstash-codec-plain#1]
Hi,

Im trying to read non UTF-8 file, it's IBM 500 file but i can't find it in the charset list provided with the plugin so i tried "US-ASCII".
Here is my config file:
input{
           file {
                path =>...
                sincedb_path => "/dev/null"
                codec => plain{charset =>"US-ASCII"}
                start_position => "beginning"
                }
        }
output{stdout{}}

It doesn't work.
What i don't understand is that i don't have any error message, logstash starts and does nothing.
on my terminal i have only this message : "Logstash startup completed"

Any help please ?
Thanks

**Comment by jordansissel** [comment]
Since this doesn't sound like a bug, and I'd like you to get the best help possible, this question may be best answered on https://discuss.elastic.co/ - can you ask there?

**Comment by OuesFa** [comment]
Ok thank you so much.
