### ISSUE TITLE
how logstash handle nil value properly with plain formater

### ISSUE THREAD

**Issue by howardyan93** [logstash-plugins/logstash-codec-plain#5]
I'm using logstash reading data from mysql to kafka. for save the disk space, I write output config as this:
  
    kafka {
        codec => plain {
            format => "%{key1},%{key2},%{key3}"
        }
    }

as I expect, by giving such input data:

    {
        key1: value1,
        key2: nil,
        key3: value3
    }

the output should as this:

    value1,,value3

but the acutal output is this:

    value1,%{key2},value3

how to set output config to convert the nil with ""?

- Version: logstash 5.6.2
- Operating System: debian8

**Comment by jsvd** [comment]
closing this and linking to two issues in core related to this situation:
Default value for sprintf interpolation (Feature) - https://github.com/elastic/logstash/pull/4416
prevent Event#sprintf from return the raw template when evaluate fails - https://github.com/elastic/logstash/issues/6363
